// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3EZ6tmMcWJvWhXoWEn_N4F1eWKSz2eiw',
    appId: '1:982794463039:android:70cc982b6297eb8dbb558a',
    messagingSenderId: '982794463039',
    projectId: 'guiadocalouro-8df99',
    databaseURL: 'https://guiadocalouro-8df99-default-rtdb.firebaseio.com',
    storageBucket: 'guiadocalouro-8df99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKAJaCX4NF1rtWZHihlEcgQowSPPND_W0',
    appId: '1:982794463039:ios:7b198c7ecf9d6077bb558a',
    messagingSenderId: '982794463039',
    projectId: 'guiadocalouro-8df99',
    databaseURL: 'https://guiadocalouro-8df99-default-rtdb.firebaseio.com',
    storageBucket: 'guiadocalouro-8df99.appspot.com',
    iosClientId: '982794463039-2ft77l9v8oufvhd0q8q2kv2en7ta79d1.apps.googleusercontent.com',
    iosBundleId: 'br.univali.guiaDoCalouro',
  );
}
